# Generated by Django 2.0.3 on 2023-11-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcreatemodel',
            name='comment_on_task',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
